version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations core && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/app/theme/static/
      - media_volume:/app/media/
    expose:
      - 8000
    env_file:
      - ./.env.prod.settings
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/theme/static/
      - media_volume:/app/media/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:


